version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: some-mysql
    restart: always
    networks:
      - sc-net
    ports:
      - 3306:3306
    volumes:
      - /data/docker/data/mysql:/var/lib/mysql  #若需要初始化，数据卷或挂载目录必须为空
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root

networks:
  sc-net:
    external: false
      